import React from 'react'
import Head from 'next/head'
function HeadTags({children,title}) {
    return (
        <Head>
            <title>{ title}</title>
            <meta name="description" content="Generated by create next app" />
            {children}
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
}

export default HeadTags
